#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 100.
# Display FizzBuzz when the number is a multiple of 3 & 5.
# Display Fizz when the number is a multiple of 3.
# Display Buzz when the number is a multiple of 5.
# Otherwise display the number: All in list format.
for i in {1..100};
do
        if (( i%3 == 0 && i%5 == 0 ))
        then
        echo "FizzBuzz"
        elif (( i % 3 == 0 ))
        then
        echo "Fizz"
        elif (( i % 5 == 0 ))
        then
        echo "Buzz"
        else
        echo "$i"
        fi
done
