#!/usr/bin/env bash
# Bash script displays for ls
# comtents of current directory
# in the ls format
# only part of the name after - is displayed

for ls in $( ls | cut -d "-" -f"2");
do
	echo "$ls";
done
